package constants;

/**
 * Stores a list of enum values used as keys by MenuManager.
 */
public enum Key {
    ALSET_LOGIN_MENU,
    EDGAR1_LOGIN_MENU,
    CUSTOMER_MENU,
    CUSTOMER_VEHICLES_MENU,
    SERVICE_MANAGER_MENU,
    VIEW_GARAGE_MENU,
    MANAGE_GARAGE_MENU,
    FINISH_GARAGE_VEHICLE_MENU,
    REMOVE_GARAGE_VEHICLE_MENU,
    SELECT_CARD_MENU,
    BROWSE_LOCATIONS_MENU,
    SELECT_MODEL_MENU,
    SELECT_YEAR_MENU,
    SELECT_OPTIONS_MENU,
    COMPLETE_ORDER_MENU,
    SELECT_LOCATION_MENU,
    MANAGE_SHOWROOM_MENU,
    VIEW_SHOWROOM_MENU,
    ADD_SHOWROOM_VEHICLE_MENU
}
