package constants;

/**
 * Stores a list of enum values used as keys by MenuManager.
 * <p>
 * Each key corresponds to an individual menu.
 */
public enum Key {
    ADD_SHOWROOM_VEHICLE_MENU,
    ALSET_LOGIN_MENU,
    BROWSE_LOCATIONS_MENU,
    EDGAR1_LOGIN_MENU,
    COMPLETE_ORDER_MENU,
    CUSTOMER_MENU,
    CUSTOMER_VEHICLES_MENU,
    FINISH_GARAGE_VEHICLE_MENU,
    MANAGE_GARAGE_MENU,
    PRODUCT_MANAGER_MENU,
    REMOVE_GARAGE_VEHICLE_MENU,
    MANAGE_LISTINGS_MENU,
    RETIRE_SHOWROOM_VEHICLE_MENU,
    MANAGE_SHOWROOM_MENU,
    SELECT_ALL_OPTIONS_MENU,
    SELECT_CARD_MENU,
    SELECT_LOCATION_MENU,
    SELECT_MODEL_MENU,
    SELECT_OPTIONS_MENU,
    SELECT_REPAIRABLE_MODEL_MENU,
    SELECT_REPAIRABLE_YEAR_MENU,
    SELECT_UNREPAIRABLE_MODEL_MENU,
    SELECT_UNREPAIRABLE_YEAR_MENU,
    SELECT_YEAR_MENU,
    SELL_LISTING_MENU,
    SERVICE_MANAGER_MENU,
    UPDATE_LISTINGS_MENU,
    VIEW_GARAGE_MENU,
    VIEW_LISTINGS_MENU,
    VIEW_SHOWROOM_MENU
}
